-- Create a table for roles
CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed the roles table with initial roles
INSERT INTO roles (name) VALUES ('user'), ('admin'), ('driver');

-- Create a table to associate users with roles
CREATE TABLE user_roles (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, role_id)
);

-- Add a role_id to the existing users table to maintain a default role
-- This is a simple way to assign a default role to new users.
-- A more robust solution might involve a trigger or function to assign roles.
ALTER TABLE users ADD COLUMN role_id BIGINT REFERENCES roles(id) DEFAULT 1; -- Default to 'user'

-- Update existing users to have the 'user' role
-- This assumes all existing users are regular users.
-- You might need to adjust this logic based on your existing data.
UPDATE users SET role_id = (SELECT id FROM roles WHERE name = 'user') WHERE role_id IS NULL;
